### ISSUE TITLE
Crashes with Sodium 0.5.11 on Minecraft 1.21.1

### ISSUE THREAD

**Issue by codyisreallycool** [isXander/xanders-sodium-options#25]
I'm not sure what mod(s) are causing it because I have a big modpack, but it seems to crash only when I change the sodium version to something like 0.5.11. I'll give the mods and crash report here:

[mods.txt](https://github.com/user-attachments/files/17309620/mods.txt)
[crash.txt](https://github.com/user-attachments/files/17309640/crash.txt)

**Comment by JoeyHamlet** [comment]
The crash is a result of Sodium 0.5.11. It works fine on the 0.6.0 beta but I find that rather annoying as I play with Nvidium which won't be updating to be compatible with any 0.6.0 build of Sodium anytime soon. 

It silently crashes with no notifications, here's my log file with the minimum amount of mods required: https://mclo.gs/vbAEaXB

**Comment by IMB11** [comment]
Sodium 0.6.0 isnt on 1.20.1

**Comment by IMB11** [comment]
I will have a look at this soon though

**Comment by JoeyHamlet** [comment]
> Sodium 0.6.0 isnt on 1.20.1

The issue is on 1.21.1 though? Not 1.20.1

**Comment by IMB11** [comment]
You need to use Sodium 0.6 for 1.21+
